Add output file names to HTML + misc
jesterKing/literate pull request #28
Opened 2023-12-02 01:29 UTC by RossBoylan

Each commit deals with a distinct issue.  In order:
1. Fix a missing `;` that triggered some errors/warnings.
2. Add filename to the codefence rendered in HTML--if one was specified
3. A bit more instruction on developing code.  As noted in that commit, I would have loved to explain how the instructions relate to what happens automatically with `F5`, but I'm not sure what that is...

2023-12-02 08:17 UTC, jesterKing requested changes
Thank you for your PR!

One small change request for the CONTRIBUTING.md.

And could you rebase on latest jesterKing:main, please?

2023-12-02 08:17 UTC, jesterKing commented on CONTRIBUTING.md
> +* Rebuild with the `VSCode` command `Literate: Process` (`literate.process`)
This step is triggered automatically on any file change in a workspace. It is not necessary to run the `literate.process` command.

Also just opening a workspace with literate files will trigger the command.

If you could remove this step.

2023-12-02 08:17 UTC, jesterKing commented on src/extension.ts
> +<div class="fragmentname">&lt;&lt;${name}&gt;&gt;${root}${add} ${fileName}</div>
I was debating with myself early on whether I wanted to show this or not. I went along with what PBR book does, and that is to not show the filenames.

For now I think it is ok to show, and introduce later an extension setting that can control the showing of filenames in rendered output.

2023-12-02 08:22 UTC, jesterKing commented on CONTRIBUTING.md
> +* Rebuild with the `VSCode` command `Literate: Process` (`literate.process`)
If you think it is important to educate users about the existance of the command then perhaps a rewording of the step to something like:

If the code changes in `.literate` files don't automatically rebuild the HTML and designated source files you can run the `VSCode` command `Literate: Process` (`literate.process`).

2023-12-02 08:23 UTC, jesterKing commented
Also, @RossBoylan, please add your name to the CONTRIBUTORS.md file in this PR :)

2023-12-05 00:44 UTC, RossBoylan commented
Will try again with new branch.

2023-12-05 00:53 UTC, closed without merging